class Config():
    COLUMNS: list = ['created_at',
                     'date',
                     'time',
                     'cashtags',
                     'timezone',
                     'username',
                     'tweet',
                     'language',
                     'replies_count',
                     'retweets_count',
                     'likes_count',
                     'hashtags',
                     'retweet',
                     'quote_url',
                     'photos',
                     'thumbnail',
                     'urls',
                     'video']
    COLUMNS_SEARCH: list = ['created_at',
                     'date',
                     'cashtags',
                     'timezone',
                     'username',
                     'tweet',
                     'language',
                     'nreplies',
                     'nretweets',
                     'nlikes',
                     'hashtags',
                     'retweet',
                     'quote_url',
                     'photos',
                     'thumbnail',
                     'urls',
                     'video']
